version: "3.4"

services:
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_CREATE_TOPICS: "sendmail_topic:3:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 104858800
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    command: sh -c "kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic sendmail_topic --group my-first-application"

  kafka-rest:
    image: confluentinc/cp-kafka-rest:4.1.1
    hostname: kafka-rest
    ports:
      - "38082:38082"
    depends_on:
      - kafka
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://kafka-rest:38082

  kafka-web-gui:
    image: tchiotludo/akhq:0.17.0
    ports:
      - "8081:8080"
    depends_on:
      - zookeeper
      - kafka-rest
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  ig_bot_db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  # auth service
  ig_bot_db_auth:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=auth_service
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=auth_service
    ports:
      - "5433:5432"
  
  auth-service:
    container_name: authentication-service
    build: src/authentication
    volumes:
      - ./src/authentication:/app/igbot-auth
    ports:
      - "3000:80"
    links:
      - kafka
    depends_on:
      - ig_bot_db_auth
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_DRIVER: postgres
      DB_USER: auth_service
      DB_PASSWORD: secret
      DB_HOST: ig_bot_db_auth
      DB_PORT: 5432
      DB_NAME: auth_service
      SERVER_POST: 80
      DOMAIN: http://localhost:3000
      KAFKA_TOPIC_SEND_MAIL: sendmail_topic

  # send mail service
  ig_bot_db_sendmail:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=sendmail_service
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=sendmail_service
    ports:
      - "5434:5432"

  sendmail-service:
    container_name: sendmail-service
    volumes:
      - ./src/mail-service:/app/igbot-sendmail
    build: src/mail-service
    ports:
      - "1997:1997"
    links:
      - kafka
      - mailhog
    depends_on:
      - ig_bot_db_sendmail
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_DRIVER: postgres
      DB_USER: sendmail_service
      DB_PASSWORD: secret
      DB_HOST: ig_bot_db_sendmail
      DB_PORT: 5432
      DB_NAME: sendmail_service
      SERVER_POST: 80
      SERVER_GRPC_PORT: 1997
      KAFKA_TOPIC_SEND_MAIL: sendmail_topic

  # automate service
  automate-service:
    container_name: automate-service
    build: src/automate
    volumes:
      - ./src/automate:/app/igbot-automate
    ports:
      - "3001:80"
    links:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
