// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: service_mail_sender.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MailSenderServiceClient is the client API for MailSenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailSenderServiceClient interface {
	SendMailVerifyAcc(ctx context.Context, in *MailVerifyAccRequest, opts ...grpc.CallOption) (*MailVerifyAccResponse, error)
	SendMailRecoveryPassword(ctx context.Context, in *MailRecoveryAccRequest, opts ...grpc.CallOption) (*MailRecoveryAccResponse, error)
}

type mailSenderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailSenderServiceClient(cc grpc.ClientConnInterface) MailSenderServiceClient {
	return &mailSenderServiceClient{cc}
}

func (c *mailSenderServiceClient) SendMailVerifyAcc(ctx context.Context, in *MailVerifyAccRequest, opts ...grpc.CallOption) (*MailVerifyAccResponse, error) {
	out := new(MailVerifyAccResponse)
	err := c.cc.Invoke(ctx, "/pb.MailSenderService/SendMailVerifyAcc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailSenderServiceClient) SendMailRecoveryPassword(ctx context.Context, in *MailRecoveryAccRequest, opts ...grpc.CallOption) (*MailRecoveryAccResponse, error) {
	out := new(MailRecoveryAccResponse)
	err := c.cc.Invoke(ctx, "/pb.MailSenderService/SendMailRecoveryPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailSenderServiceServer is the server API for MailSenderService service.
// All implementations must embed UnimplementedMailSenderServiceServer
// for forward compatibility
type MailSenderServiceServer interface {
	SendMailVerifyAcc(context.Context, *MailVerifyAccRequest) (*MailVerifyAccResponse, error)
	SendMailRecoveryPassword(context.Context, *MailRecoveryAccRequest) (*MailRecoveryAccResponse, error)
	mustEmbedUnimplementedMailSenderServiceServer()
}

// UnimplementedMailSenderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailSenderServiceServer struct {
}

func (UnimplementedMailSenderServiceServer) SendMailVerifyAcc(context.Context, *MailVerifyAccRequest) (*MailVerifyAccResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMailVerifyAcc not implemented")
}
func (UnimplementedMailSenderServiceServer) SendMailRecoveryPassword(context.Context, *MailRecoveryAccRequest) (*MailRecoveryAccResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMailRecoveryPassword not implemented")
}
func (UnimplementedMailSenderServiceServer) mustEmbedUnimplementedMailSenderServiceServer() {}

// UnsafeMailSenderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailSenderServiceServer will
// result in compilation errors.
type UnsafeMailSenderServiceServer interface {
	mustEmbedUnimplementedMailSenderServiceServer()
}

func RegisterMailSenderServiceServer(s grpc.ServiceRegistrar, srv MailSenderServiceServer) {
	s.RegisterService(&MailSenderService_ServiceDesc, srv)
}

func _MailSenderService_SendMailVerifyAcc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailVerifyAccRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailSenderServiceServer).SendMailVerifyAcc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MailSenderService/SendMailVerifyAcc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailSenderServiceServer).SendMailVerifyAcc(ctx, req.(*MailVerifyAccRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailSenderService_SendMailRecoveryPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailRecoveryAccRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailSenderServiceServer).SendMailRecoveryPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MailSenderService/SendMailRecoveryPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailSenderServiceServer).SendMailRecoveryPassword(ctx, req.(*MailRecoveryAccRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailSenderService_ServiceDesc is the grpc.ServiceDesc for MailSenderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailSenderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MailSenderService",
	HandlerType: (*MailSenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMailVerifyAcc",
			Handler:    _MailSenderService_SendMailVerifyAcc_Handler,
		},
		{
			MethodName: "SendMailRecoveryPassword",
			Handler:    _MailSenderService_SendMailRecoveryPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_mail_sender.proto",
}
